---
driver:
  name: vagrant
  provider: libvirt

provisioner:
  name: chef_zero
  product_name: chef
  deprecations_as_errors: true
  enforce_idempotency: false # TODO: improve cookbook to enforce idempotency
  multiple_converge: 2

verifier:
  name: inspec

platforms:
  - name: debian/stretch64
  - name: centos/7
  - name: generic/ubuntu1804

suites:
  - name: default
    run_list:
      - recipe[postfix::server]
      - recipe[zeyple::default]
      - recipe[zeyple_test::default]
    attributes:
      zeyple:
        gpg:
          keys: ["0xEEC73D5809A98A9B"]
